spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to VPGBank loans related prod APIs "
  contactDetails:
    name: "sam altman - Product Owner"
    email: "sam@vpgbank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956