services:
    accounts:
      image: "shivrajgodle/accounts:s4"
      container_name: accounts-ms
      ports:
        - "8080:8080"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - vpgbank
    loans:
      image: "shivrajgodle/loan:s4"
      container_name: loan-ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - vpgbank
    cards:
      image: "shivrajgodle/cards:s4"
      container_name: cards-ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - vpgbank
networks:
  vpgbank:
    driver: "bridge"