spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to VPGBank loans related QA APIs "
  contactDetails:
    name: "james Marita - QA Lead"
    email: "james@vpgbank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467